### ISSUE TITLE
Error: Refreshtoken Incorrect!

### ISSUE THREAD

**Issue by XiaolanX** [Runtus/koishi-plugin-rpixiv#12]
状态
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz

Binaries:
    Node: 20.9.0
    Yarn: 4.0.1

Koishi:
    Core: 4.15.5
    Console: 5.19.1

服务器在香港，通过浏览器测试pixiv可正常进入，确认过token无误，但是能用的概率很小，大部分时候都是token错误的情况，甚至可能刚用一次下一次就开始token报错=-=

**Comment by XiaolanX** [comment]
报错都是清一色的：
[E] rpixiv-bot Error: Refreshtoken Incorrect!
                            at /home/koishi/node_modules/runtu-pixiv-sdk/dist/index.cjs:30816:11
                            at Generator.next (<anonymous>)
                            at fulfilled (/home/koishi/node_modules/runtu-pixiv-sdk/dist/index.cjs:37:58)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Runtus** [comment]
抱歉，我这里看看是什么问题

**Comment by Runtus** [comment]
我这里无法复现问题，麻烦你发我下你的配置页面我看下。
关于都是清一色的`Refreshtoken incorrect`，是底层的请求库的问题，那个我会做重构，把问题细化，确实带来了很不直观的报错

**Comment by XiaolanX** [comment]
系统已经重装了，装了Windows系统后一直无法启动插件，错误为：当前配置项不满足约束，请检查配置！
应该只需要填写token才对，而且也填写了，但就是没办法启用

**Comment by Runtus** [comment]
@XiaolanX 这几天有些忙抱歉，我刚刚查看了下是推送配置的问题，最近我先把这个功能下线了，后续我忙完了再来fix。
